# Generated by Django 5.2.3 on 2025-06-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
